'use client';

import { useEffect, useState } from 'react';
import { jsPDF } from 'jspdf';

type PendingReport = {
  productName: string;
  companyName: string;
  preparedFor: string;
  categoryLabel: string;
  roleLabel: string;
  reportDate: string;
  reportId: string;
  regulations: string[];
  evidence: string[];
  risks: string[];
};

function safeFileName(value: string) {
  return value
    .trim()
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'compliance-report';
}

function generatePdf(report: PendingReport) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const width = 210;
  const left = 18;
  const right = 192;
  let y = 20;

  const line = () => {
    doc.setDrawColor(220, 226, 235);
    doc.line(left, y, right, y);
    y += 7;
  };

  const heading = (text: string) => {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text(text, left, y);
    y += 7;
  };

  const paragraph = (text: string, size = 10) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(size);
    doc.setTextColor(55, 65, 81);
    const lines = doc.splitTextToSize(text, right - left);
    if (y + lines.length * 5 > 280) {
      doc.addPage();
      y = 20;
    }
    doc.text(lines, left, y);
    y += lines.length * 5 + 3;
    doc.setTextColor(17, 24, 39);
  };

  const bullets = (items: string[]) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    for (const item of items) {
      const lines = doc.splitTextToSize(item, right - left - 7);
      if (y + lines.length * 5 > 280) {
        doc.addPage();
        y = 20;
      }
      doc.text('•', left, y);
      doc.text(lines, left + 6, y);
      y += lines.length * 5 + 2;
    }
    y += 2;
  };

  doc.setFillColor(11, 18, 32);
  doc.rect(0, 0, width, 34, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('RegMetric', left, 15);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Professional Product Compliance Report', left, 22);

  doc.setFont('helvetica', 'bold');
  doc.text(report.reportId || 'RegMetric Report', right, 14, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.text(report.reportDate || '', right, 21, { align: 'right' });

  y = 47;
  doc.setTextColor(17, 24, 39);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text(report.productName || 'Unnamed Product', left, y);
  y += 8;
  paragraph(`${report.categoryLabel} · European Union · ${report.roleLabel}`, 10);

  if (report.companyName || report.preparedFor) {
    line();
    if (report.companyName) paragraph(`Company / Organization: ${report.companyName}`);
    if (report.preparedFor) paragraph(`Prepared for: ${report.preparedFor}`);
  }

  line();
  heading('1. Executive Summary');
  paragraph(
    `This professional report summarizes ${report.regulations.length} potentially relevant compliance areas identified during the RegMetric assessment. Final applicability must be confirmed against the finished product specification, intended use and applicable law.`
  );

  heading('2. Regulatory Areas');
  bullets(report.regulations);

  heading('3. Evidence Checklist');
  bullets(report.evidence);

  heading('4. Potential Gaps');
  bullets(report.risks);

  heading('5. Recommended Follow-Up');
  bullets([
    'Confirm the exact legal scope against final product specifications.',
    'Map each applicable requirement to current technical and supplier evidence.',
    'Record missing evidence, owners and target completion dates.',
    'Review labels, declarations and market-specific registrations before launch.'
  ]);

  line();
  paragraph(
    'Generated by RegMetric. This report is a compliance research aid and does not constitute legal advice or a final conformity determination.',
    8
  );

  doc.save(`RegMetric-${safeFileName(report.productName)}-${report.reportId || 'report'}.pdf`);
}

export default function PaidReportDownload() {
  const [status, setStatus] = useState<'checking' | 'ready' | 'error'>('checking');
  const [message, setMessage] = useState('Verifying your PayPal payment…');
  const [report, setReport] = useState<PendingReport | null>(null);

  useEffect(() => {
    const run = async () => {
      const params = new URLSearchParams(window.location.search);
      const orderId = params.get('token');

      if (!orderId) {
        setStatus('error');
        setMessage('PayPal order ID is missing. Return to the report and start checkout again.');
        return;
      }

      const raw = window.localStorage.getItem('regmetric_pending_paid_report');
      if (!raw) {
        setStatus('error');
        setMessage('Your report draft was not found in this browser. Return to Reports and rebuild it.');
        return;
      }

      let pending: PendingReport;
      try {
        pending = JSON.parse(raw) as PendingReport;
      } catch {
        setStatus('error');
        setMessage('The saved report draft could not be read.');
        return;
      }

      try {
        const response = await fetch('/api/paypal/capture-order', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ orderId })
        });
        const data = await response.json();

        if (!response.ok || !data.paid) {
          throw new Error(data.error || 'Payment could not be verified.');
        }

        setReport(pending);
        setStatus('ready');
        setMessage('Payment verified. Your professional PDF is ready.');
        window.localStorage.setItem(
          'regmetric_last_paid_order',
          JSON.stringify({ orderId, verifiedAt: new Date().toISOString() })
        );
      } catch (error) {
        setStatus('error');
        setMessage(error instanceof Error ? error.message : 'Payment verification failed.');
      }
    };

    run();
  }, []);

  return (
    <div className="payment-result-card">
      <span className="card-badge">
        {status === 'ready' ? 'Payment Verified' : status === 'error' ? 'Action Required' : 'Verifying'}
      </span>
      <h1>
        {status === 'ready'
          ? 'Your professional report is ready.'
          : status === 'error'
            ? 'We could not unlock the report yet.'
            : 'Confirming your payment…'}
      </h1>
      <p>{message}</p>

      {status === 'ready' && report && (
        <div className="payment-result-actions">
          <button className="button button-primary" type="button" onClick={() => generatePdf(report)}>
            Download Professional PDF
          </button>
          <a className="button button-secondary" href="/reports">Back to Reports</a>
        </div>
      )}

      {status === 'error' && (
        <div className="payment-result-actions">
          <a className="button button-primary" href="/reports">Return to Reports</a>
          <a className="button button-secondary" href="mailto:cnhhryp@gmail.com">Contact Support</a>
        </div>
      )}
    </div>
  );
}
